import logging
from pathlib import Path
from datetime import datetime

# Logging setup 
def create_logger(
    name: str,
    log_dir: str = "logs",
    level: int = logging.INFO,
    *, 
    filename: str = None,
    include_console: bool = True,
    time_format: str = "%Y%m%d_%H%M%S",
) -> logging.Logger:
    """
    Create (or reconfigure) a logger that writes to a timestamped file.
    
    Args:
        name: Name of the logger.
        log_dir: Directory where log file will be placed (created if missing).
        level: Logging level.
        filename: Explicit filename to use instead of autogenerated one.
        include_console: Whether to also log to stdout.
        time_format: strftime format for the timestamp in autogenerated filename.
        
    Returns:
        Configured logging.Logger instance.
    """
    path = Path(log_dir)
    path.mkdir(parents=True, exist_ok=True)

    if filename is None:
        timestamp = datetime.now().strftime(time_format)
        safe_name = name.replace(" ", "_")
        filename = f"{safe_name}_{timestamp}.log"

    log_file_path = path / filename

    logger = logging.getLogger(name)
    logger.setLevel(level)

    if logger.hasHandlers():
        logger.handlers.clear()

    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )

    file_handler = logging.FileHandler(log_file_path, encoding="utf-8")
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)

    if include_console:
        console_handler = logging.StreamHandler()
        console_handler.setFormatter(formatter)
        logger.addHandler(console_handler)

    return logger